SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_AvailableActionContext "{69F1A2B3C4D50060}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{69F1A2B3C4D50061}" {
    }
   }
   m_sTag "LL_VON"
   m_sAction "LL_RadioEarCycle"
   m_sName "#LL-Hint_RadioEarCycle"
  }
  SCR_AvailableActionContext "{69F1A2B3C4D50062}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{69F1A2B3C4D50063}" {
    }
   }
   m_sTag "LL_VON"
   m_sAction "LL_RadioFrequency"
   m_sName "#LL-Hint_RadioFrequency"
  }
  SCR_AvailableActionContext "{69F1A2B3C4D50064}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{69F1A2B3C4D50065}" {
    }
   }
   m_sTag "LL_VON"
   m_sAction "LL_RadioVolumeUp"
   m_sName "#LL-Hint_RadioVolumeUp"
  }
  SCR_AvailableActionContext "{69F1A2B3C4D50066}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{69F1A2B3C4D50067}" {
    }
   }
   m_sTag "LL_VON"
   m_sAction "LL_RadioVolumeDown"
   m_sName "#LL-Hint_RadioVolumeDown"
  }
 }
}
