SCR_MapMarkerConfig {
 m_aMarkerEntryConfigs {
  LL_MapMarkerEntryPlaced "{1D20000000000001}" {
   m_sMenuDescription "#LL-Markers_PlaceMarker"
   m_aIcons {
    LL_MarkerIconEntry "{1D20000000000012}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "dot"
     m_sDisplayName "#LL-Markers_Dot"
     m_fLabelInk 0.25
    }
    LL_MarkerIconEntry "{1D20000000000010}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "fire-team"
     m_sDisplayName "#LL-Markers_FireTeam"
    }
    LL_MarkerIconEntry "{1D20000000000011}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "vehicle"
     m_sDisplayName "#LL-Markers_Vehicle"
     m_fLabelInk 0.9
    }
    LL_MarkerIconEntry "{1D20000000000013}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "landing"
     m_sDisplayName "#LL-Markers_Landing"
     m_fLabelInk 0.85
    }
    LL_MarkerIconEntry "{1D20000000000014}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "flag"
     m_sDisplayName "#LL-Markers_Flag"
     m_fLabelInk 0.5
    }
    LL_MarkerIconEntry "{1D20000000000015}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "exclamation"
     m_sDisplayName "#LL-Markers_Warning"
     m_fLabelInk 0.22
    }
    LL_MarkerIconEntry "{1D20000000000016}" {
     m_sIconImageset "{CCED36C0D903191D}UI/Textures/GroupManagement/FlagIcons/LiteIcons.imageset"
     m_sIconImagesetQuad "question"
     m_sDisplayName "#LL-Markers_Question"
     m_fLabelInk 0.28
    }
   }
   m_aPlacedMarkerColors {
    LL_MarkerColorEntry "{1D20000000000020}" {
     m_sTakeColorFromFaction "US"
     m_Color 0.018 0.216 0.874 1
     m_sName "#LL-Markers_ColorBlue"
    }
    LL_MarkerColorEntry "{1D20000000000021}" {
     m_sTakeColorFromFaction "USSR"
     m_Color 0.842 0.078 0.078 1
     m_sName "#LL-Markers_ColorRed"
    }
    LL_MarkerColorEntry "{1D20000000000022}" {
     m_sTakeColorFromFaction "FIA"
     m_Color 0.014 0.646 0.008 1
     m_sName "#LL-Markers_ColorGreen"
    }
    LL_MarkerColorEntry "{1D20000000000023}" {
     m_Color 1 0.716 0.141 1
     m_sName "#LL-Markers_ColorYellow"
    }
   }
  }
 }
}
