SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{CC3A9133A98FD0D1}" {
   SystemLocation Server
   SystemPoints 0x2000 0x10
   Config "{BB74E229540B74C1}Configs/Systems/Persistence/LL_Persistence.conf"
  }
 }
}
