SCR_MissionHeader {
 World "{317D819C19DDD4D7}worlds/Arland/LobbyDemo.ent"
 m_sName "#LL-Mission_DemoName"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "#LL-Mission_DemoDescription"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}