MenuManager {
 MenuPresets {
  MenuPreset CoopLobby {
   Layout "{5910780E972548BA}UI/Lobby/CoopLobby.layout"
   ActionContext "LL_LobbyContext"
   Class "LL_CoopLobby"
  }
  MenuPreset BriefingMapMenu {
   Layout "{8D52F3BA1C6E429A}UI/Briefing/BriefingMapMenu.layout"
   ActionContext "LL_BriefingMapContext"
   Class "LL_BriefingMapMenu"
  }
  MenuPreset SpectatorMenu {
   Layout "{6C73A4D8E91B527F}UI/Spectator/SpectatorMenu.layout"
   ActionContext "LL_SpectatorContext"
   Class "LL_SpectatorMenu"
  }
  MenuPreset GameMapMenu {
   Layout "{2A6D4C9845126417}UI/Map/GameMapMenu.layout"
   ActionContext "LL_BriefingMapContext"
   Class "LL_GameMapMenu"
  }
  MenuPreset StatsAdminMenu {
   Layout "{8C3E5A19D2B47700}UI/Stats/StatsAdminPanel.layout"
   ActionContext "LL_StatsContext"
   Class "LL_StatsAdminPanel"
  }
  MenuPreset StatsScreenMenu {
   Layout "{8C3E5A19D2B47600}UI/Stats/StatsScreen.layout"
   ActionContext "LL_StatsContext"
   Class "LL_StatsScreen"
  }
 }
}