SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{69D71D9B3201A0E9}" {
   m_sName "lite_lobby"
   m_sDisplayName "#LL-Keybind_Category"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{69D71D9B32000E81}" {
     m_sActionName "LL_VoNModeCycle"
     m_sDisplayName "#LL-Keybind_VoNModeCycle"
    }
    SCR_KeyBindingEntry "{69F1A2B3C4D50044}" {
     m_sActionName "LL_MapMarkerInfo"
     m_sDisplayName "#LL-Keybind_MapMarkerInfo"
    }
    SCR_KeyBindingEntry "{69D8B4C2F1E20330}" {
     m_sActionName "LL_EffectsVolumeDown"
     m_sDisplayName "#LL-Keybind_EffectsVolumeDown"
    }
    SCR_KeyBindingEntry "{69D8B4C2F1E20331}" {
     m_sActionName "LL_EffectsVolumeUp"
     m_sDisplayName "#LL-Keybind_EffectsVolumeUp"
    }
    SCR_KeyBindingEntry "{69F1A2B3C4D50040}" {
     m_sActionName "LL_RadioEarCycle"
     m_sDisplayName "#LL-Keybind_RadioEarCycle"
    }
    SCR_KeyBindingEntry "{69F1A2B3C4D50041}" {
     m_sActionName "LL_RadioFrequency"
     m_sDisplayName "#LL-Keybind_RadioFrequency"
    }
    SCR_KeyBindingEntry "{69F1A2B3C4D50042}" {
     m_sActionName "LL_RadioVolumeUp"
     m_sDisplayName "#LL-Keybind_RadioVolumeUp"
    }
    SCR_KeyBindingEntry "{69F1A2B3C4D50043}" {
     m_sActionName "LL_RadioVolumeDown"
     m_sDisplayName "#LL-Keybind_RadioVolumeDown"
    }
   }
  }
 }
}