PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Collections {
  PersistenceCollection "{43DB609DE0025271}" {
   Name "LL_Lobby"
   Storage "{62488048AF9D8A55}"
  }
 }
 Bundles {
  PersistenceBundle WorldState {
   Collections +{
    "{43DB609DE0025271}"
   }
  }
 }
 Configurations {
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Lobby {
     Configurations {
      StatePersistenceConfig "{56D59545F94C6631}" {
       SelfDelete 0
       Collection "{43DB609DE0025271}"
       Serializer LL_SessionSerializer "{6218E63C9420D0F8}" {
       }
      }
      StatePersistenceConfig "{D5E57E2CF1749B8C}" {
       SelfDelete 0
       Collection "{43DB609DE0025271}"
       Serializer LL_TriggerSerializer "{CE42241EF72902BB}" {
       }
      }
      StatePersistenceConfig "{33819C2DD6B0D622}" {
       SelfDelete 0
       Collection "{43DB609DE0025271}"
       Serializer LL_MarkerSerializer "{85C5696CFA283E47}" {
       }
      }
     }
    }
   }
  }
 }
 PersistentStates +{
  LL_SessionData "{FA8D229364EC0346}" {
  }
  LL_TriggerData "{4E842B51108E4385}" {
  }
  LL_MarkerData "{87DDA845A5363717}" {
  }
 }
}
