PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Collections {
  PersistenceCollection "{43DB609DE0025271}" {
   Name "LL_Lobby"
   Storage "{62488048AF9D8A55}"
  }
 }
 Bundles {
  PersistenceBundle WorldState {
   Collections +{
    "{43DB609DE0025271}"
   }
  }
 }
}
